---
title: "relatorio_JV"
author: "Ayrton/Thais"
date: "2025-08-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### pacotes

```{r pacotes, message=FALSE, warning=FALSE, include=FALSE}
 

# Configuração inicial
pacman::p_load(
  tidyverse,sf,magrittr,fuzzyjoin,
  lubridate,ggpubr,cowplot,gtable,
  nowcaster, AlertTools,epical,
  assertthat, patchwork, kableExtra,kable
)

source("./funcoes_submunicipal.R")

ano_atual <- year(Sys.Date())
```


```{r Carregando dados, message=FALSE, warning=FALSE, cache=T, include=FALSE}


# DADOS REFERÊNCIA
jv_pop <- read_csv2(
  file = "./dados_ref/joinville_pop.csv") %>% 
  mutate(nome_bairr = normalizar_bairro(nome_bairr)
) %>% select(nome_bairr,id_bairro,pop)

jv_ref <- read_csv2(
  file = "./dados_ref/joinville_ref.csv",
  locale = locale(encoding = "Latin1")) %>% 
  mutate(nome_bairr = normalizar_bairro(nome_bairr)
)

jv_shp <- read_sf("./shapes/Joishapes/joiBairros/joiBairros.shp")
distritos_shp <- read_sf("./shapes/Joishapes/joiDistritos/joiDistr.shp") %>% 
  rename(distrito = Distrito)
jvmun_shape <- geobr::read_municipality(code_muni = 4209102)

# Dados para níveis de alerta
load("./Rt/clijv.RData") #substituir pelo downscale 
load("./Rt/paramsjv.RData")

##### DADOS DENGUE
## (esse carregamento só é feito enquanto não enviado
## para o Vínicius rodar direto no pipeline)

if(FALSE) {
#dg_arquivos <- c("./dados_casos/DENGON_SC_2024.dbf") #, "./dados_casos/DENGON_SC.dbf")
#ck_arquivos <- c("./dados_casos/CHIKON_SC.dbf")

# dg24 <- map_dfr(dg_arquivos, ler_dados_dengue)
# dg25 <- read.csv("./dados_casos/DENGON_SC2025_30.csv") %>%
#     filter(ID_MUNICIP == "420910", ID_MN_RESI == "420910") %>%  # Joinville
#     select(NU_NOTIFIC, NU_ANO, SEM_NOT, SG_UF_NOT, ID_UNIDADE,
#            ID_BAIRRO, NM_BAIRRO,  ID_MN_RESI, CLASSI_FIN,
#            DT_SIN_PRI, DT_DIGITA) %>%
#   mutate(NU_ANO = as.numeric(NU_ANO),
#          SEM_NOT = as.numeric(SEM_NOT),
#          NU_NOTIFIC = as.numeric(NU_NOTIFIC),
#          SG_UF_NOT = as.numeric(SG_UF_NOT),
#          ID_MN_RESI = as.numeric(ID_MN_RESI))
# 
# dg24 <- read.csv("./dados_casos/DENGON_SC2024.csv") %>%
#     filter(ID_MUNICIP == "420910", ID_MN_RESI == "420910") %>%  # Joinville
#     select(NU_NOTIFIC, NU_ANO, SEM_NOT, SG_UF_NOT, ID_UNIDADE,
#            ID_BAIRRO, NM_BAIRRO, ID_MN_RESI, CLASSI_FIN, DT_NOTIFIC,
#            DT_SIN_PRI, DT_DIGITA)
}

## DENGUE 2024
dg24 <- read.csv("./dados_casos/ok/DENGON_SC2024.csv") %>%
    filter(ID_MUNICIP == "420910", ID_MN_RESI == "420910") %>%  # Joinville
    select(NU_NOTIFIC, NU_ANO, SEM_NOT, SG_UF_NOT, ID_UNIDADE,
           ID_BAIRRO, NM_BAIRRO, ID_MN_RESI, CLASSI_FIN, DT_NOTIFIC,
           DT_SIN_PRI, DT_DIGITA) %>% arrange(SEM_NOT) %>% 
  mutate(arbo = "dengon")


## DENGUE 2025 até SE 31
dg25 <- read.csv("./dados_casos/ok/DENGON_SC2025_32.csv") %>%
    filter(ID_MUNICIP == "420910", ID_MN_RESI == "420910") %>%  # Joinville
    select(NU_NOTIFIC, NU_ANO, SEM_NOT, SG_UF_NOT, ID_UNIDADE,
           ID_BAIRRO, NM_BAIRRO,  ID_MN_RESI, CLASSI_FIN, DT_NOTIFIC,
           DT_SIN_PRI, DT_DIGITA) %>% arrange(SEM_NOT) %>% 
  mutate(arbo = "dengon")

## CHIKUNGUNYA 2024
ck24 <- read.csv("./dados_casos/ok/CHIKON_SC2024.csv")%>%
    filter(ID_MUNICIP == "420910", ID_MN_RESI == "420910") %>%  # Joinville
    select(NU_NOTIFIC, NU_ANO, SEM_NOT, SG_UF_NOT, ID_UNIDADE,
           ID_BAIRRO, NM_BAIRRO, ID_MN_RESI, CLASSI_FIN, DT_NOTIFIC,
           DT_SIN_PRI, DT_DIGITA) %>% 
    mutate(arbo = "chikon")

## CHIKUNGUNYA 2025 até SE 31
ck25 <- read.csv("./dados_casos/ok/CHIKON_SC2025_32.csv") %>%
    filter(ID_MUNICIP == "420910", ID_MN_RESI == "420910") %>%  # Joinville
    select(NU_NOTIFIC, NU_ANO, SEM_NOT, SG_UF_NOT, ID_UNIDADE,
           ID_BAIRRO, NM_BAIRRO,  ID_MN_RESI, CLASSI_FIN, DT_NOTIFIC,
           DT_SIN_PRI, DT_DIGITA) %>% 
    mutate(arbo = "chikon")

df_mun <- rbind(dg24,dg25,ck24,ck25)


##### DADOS API
dados_api_dengon <- read.csv('./dados_casos/ok/dengue_1-32.csv') %>%
  select(SE, nivel, receptivo, Rt, casos, p_inc100k, tempmin) %>%
  mutate(ano = substr(SE, 1, 4)) %>%
  #filter(ano %in% c(ano_atual-1, ano_atual)) |>
  mutate(geometry = jvmun_shape$geom,
         arbo = "dengon")

dados_api_chikon <- read.csv('./dados_casos/ok/chikungunya_1-32.csv') %>%
  select(SE, nivel, receptivo, Rt, casos, p_inc100k, tempmin) %>%
  mutate(ano = substr(SE, 1, 4)) %>%
  #filter(ano %in% c(ano_atual-1, ano_atual)) |>
  mutate(geometry = jvmun_shape$geom,
         arbo = "chikon")

dados_api <-  rbind(dados_api_dengon,dados_api_chikon)

# Semanas alvo
weeks_2_plot <- tail(
  sort(unique(factor(df_mun$SEM_NOT))), 3
)
```

#### Processando dados

```{r processar_dados, include = FALSE}

##### # PROCESSAR DADOS PRINCIPAIS
df_mun %<>% 
  #filter(NU_ANO %in% c(ano_atual-1, ano_atual)) %>%
   mutate(DT_DIGITA = as.Date(DT_DIGITA, format = "%Y-%m-%d"),
          DT_SIN_PRI = as.Date(DT_SIN_PRI, format = "%Y-%m-%d"),
          DT_NOTIFIC = as.Date(DT_NOTIFIC, format = "%Y-%m-%d")) %>% 
  rename_with(tolower)


#### NORMALIZAR NOMES DE BAIRROS E FAZER MATCHING
df_mun_filtrado <- df_mun %>%
  mutate(nm_bairro_norm = normalizar_bairro(nm_bairro)) %>%
  filter(!is.na(nm_bairro_norm))

df_mun_ok <- stringdist_inner_join(
  df_mun_filtrado,
  tibble(nm_bairro_ref = jv_ref$nome_bairr),
  by = c("nm_bairro_norm" = "nm_bairro_ref"),
  method = "lv",
  max_dist = 2
)

##### CLASSIFICAR BAIRROS EM DISTRITOS
res_distritos <- classificar_bairros_distrito(
    sp_distritos = distritos_shp,
    sp_bairros = jv_shp
  ) %>% 
  mutate(nome_bairr = normalizar_bairro(nome_bairr)) 


##### SUMARIZAR POR BAIRRO E SE
df_bairros <- df_mun_ok %>%
  count(arbo, nm_bairro_ref,
        sem_not, name = "notificações") %>%
  mutate(sem_not = as.numeric(sem_not)) %>% 
  completar_dados_bairros(
    bairros_unicos = unique(df_mun_ok$nm_bairro_ref),
    se_var = "sem_not",
    nm_bairr_var = "nm_bairro_ref"
  ) %>%
  left_join(jv_pop,
            by = c("nm_bairro_ref" = "nome_bairr")) %>%
  left_join(jv_shp,
            by = c("nm_bairro_ref"= "nome_bairr")) %>% 
  left_join(res_distritos,
            by = c("nm_bairro_ref"= "nome_bairr")) %>% 
  select(nm_bairro_ref, sem_not, arbo, distrito, 
         notificações,pop,geometry,geometry_distritos)

df_distritos <- df_bairros %>%
  group_by(distrito,sem_not, arbo) %>%
  summarise(
    pop = sum(pop, na.rm = TRUE),
    notificações = sum(notificações, na.rm = TRUE),
    geometry = st_union(geometry_distritos),
    .groups = "drop"
  ) %>%
  mutate(
    inc = notificações/pop*1e5,
    ano = substr(sem_not, 1, 4)
  ) %>%
  filter(ano %in% c(ano_atual-1, ano_atual))
  
##### DADOS NOWCASTING MUNICÍPIO
nowcastdg_mun <- df_mun  %>% 
  select(arbo,nu_notific, nu_ano, sem_not, dt_sin_pri, dt_digita,dt_notific) %>%
  filter(year(dt_sin_pri) %in% c(ano_atual-2, ano_atual-1, ano_atual)) %>%
  drop_na(dt_sin_pri, dt_digita) %>%
  select(arbo,dt_digita, dt_sin_pri,dt_notific)


##### DADOS NOWCASTING DISTRITO
nowcastdg_dis <- df_mun_ok %>% 
  select(nu_notific, sem_not, nm_bairro_ref,
         dt_sin_pri, dt_digita, dt_notific) %>% 
  left_join(res_distritos %>% 
              select(nome_bairr,distrito),
            by = c("nm_bairro_ref"="nome_bairr")) %>% na.omit() %>% 
  select(dt_digita, dt_sin_pri,dt_notific,distrito)


##### ADICIONAR SHAPE MUNICIPIO NOS DADOS API (acho que não está sendo utilizado)
dados_api_dengon$geometry_mun <- sf::st_union(jvmun_shape$geom) 
dados_api_chikon$geometry_mun <- sf::st_union(jvmun_shape$geom) 



```

#### Calculando nível de alerta

```{r calculando_alerts, include=FALSE}

#### DISTRITOS

df_distritos <- df_distritos %>% 
  rename(casos = notificações) %>% 
  left_join(dados_api %>% 
              ungroup() %>% 
              select(SE, tempmin,arbo) %>% 
              rename(temp_min = tempmin),
            by = c("sem_not" = "SE","arbo")
) %>% 
  mutate(
    id_distrito = case_when(
      distrito == "Distrito Norte" ~ 1,
      distrito == "Distrito Sul" ~ 2,
      distrito == "Distrito Centro" ~ 3
    ),
    ano = as.numeric(substr(sem_not, 1, 4)),
    inc = casos/pop*1e5
) %>% as.data.frame()

# Calcular alertas para todos os distritos
ids_distrito <- unique(df_distritos$id_distrito)
nomes_distrito <- unique(df_distritos$distrito)

df_distritos <- map2_dfr(
  ids_distrito, nomes_distrito, calcular_alerta,
  data = df_distritos,
  coluna_id = "id_distrito",
  gtdist = "normal",
  meangt = 3,
  sdgt = 1
  )

##### BAIRROS

df_bairros <- df_bairros %>% 
  rename(casos = notificações) %>% 
  left_join(dados_api %>% 
              ungroup() %>% 
              select(SE, tempmin,arbo) %>% 
              rename(temp_min = tempmin),
            by = c("sem_not" = "SE","arbo")
) %>% 
  mutate(
  id_bairro = as.numeric(factor(nm_bairro_ref)),
    ano = as.numeric(substr(sem_not, 1, 4)),
    inc = casos/pop*1e5
) %>% as.data.frame()

# Calcular alertas para todos os distritos
ids_bairro <- unique(df_bairros$id_bairro)
nomes_bairro <- unique(df_bairros$nm_bairro_ref)

df_bairros <- map2_dfr(
  ids_bairro, nomes_bairro, calcular_alerta,
  data = df_bairros,
  coluna_id = "id_bairro",
  gtdist = "normal",
  meangt = 3,
  sdgt = 1
  ) %>% na.omit()

```

#### Nowscating

```{r nowscating, include=FALSE}

#### MUNICIPIO

mun_nowscasting <-  nowcasting_inla(
  dataset = nowcastdg_mun,
  data.by.week = TRUE,
  date_onset = dt_sin_pri,
  date_report = dt_digita,
  K = 1, Dmax = 5
)

# Preparar dados observados (incluir arbo para selecionar apenas degon aqui)
mun_observados <- nowcastdg_mun %>%
  filter(arbo == "dengon") %>% 
  mutate(
    dt_event = dt_sin_pri,
    epiweek = epical::epi_week(dt_event)[[1]],
    ano = year(dt_event),
    ano_epi = paste0(ano, str_pad(epiweek, width = 2, pad = "0")) 
  ) %>% 
  count(ano_epi, dt_event, name = "total_Y") %>%
  filter(total_Y != 0 & ano_epi >= paste0(ano_atual - 1, "01")) %>%
  group_by(ano_epi) %>%
  summarise(total_Y = sum(total_Y)) %>%
  left_join(
    dados_api %>% filter(arbo == "dengon") %>% 
      mutate(SE = as.character(SE)) %>% select(SE, nivel),
    by = c("ano_epi" = "SE")
  )

mun_nowcast <- mun_nowscasting$total %>%
  mutate(
    ano = year(dt_event),
    epiweek = epical::epi_week(dt_event)[[1]],
    ano_epi = case_when(
      epiweek == 1 & lag(epiweek, default = 52) == 52 ~ 
        paste0(year(dt_event) + 1, str_pad(epiweek, width = 2, pad = "0")),
      TRUE ~ paste0(year(dt_event), str_pad(epiweek, width = 2, pad = "0"))
    ),
    type = case_when(
      ano_epi > as.numeric(as.character(weeks_2_plot[3])) ~ 'Forecasting',
      TRUE ~ "Nowcasting"
    )
  )

jv_mun_nowscat <- list(mun_observados = mun_observados,
                       mun_nowcast = mun_nowcast)

#### DISTRITOS

# Processar nowcast para todos os distritos
distritos_nomes <- unique(df_distritos$distrito)

# Processar dados de nowcast para todos os distritos
jv_distritos_nowcast <- map(
  distritos_nomes,
  processar_nowcast_distrito,
  dados_distrito = nowcastdg_dis ,
  K = 1,
  Dmax = 5)

names(jv_distritos_nowcast) <- distritos_nomes

###### incluir no código e já calcular a incidência
populacoes_distritos <- c(
  "Distrito Centro" = 174752,
  "Distrito Norte" = 147823,
  "Distrito Sul" = 174616
)
```

#### Agrupando dados em lista e limpando ambiente

```{r juntando_dados_limpando}

jv_intr_dados = list(df_mun = df_mun_ok,
                     df_mun_ok = df_mun_ok,
                     df_bairros = df_bairros,
                     df_distritos = df_distritos,
                     nowcastdg_mun = nowcastdg_mun,
                     nowcastdg_dis = nowcastdg_dis,
                     dados_api_dengon = dados_api_dengon,
                     dados_api_chikon = dados_api_chikon
  )

#### REMOVER OBJETOS
 rm(dg24,dg25,ck24,ck25,df_mun,df_mun_filtrado,
    df_mun_ok,df_bairros,df_distritos,nowcastdg_mun,
    nowcastdg_dis,dados_api_chikon,dados_api_dengon,
    res_distritos,jv_pop,jv_ref)

```

#### 


```{r}

```


